apiVersion: 1

contactPoints:
  - orgId: 1
    name: whennawa-email
    receivers:
      - uid: whennawa-email
        type: webhook
        settings:
          url: http://host.docker.internal:18080/grafana-alert
          httpMethod: POST
          maxAlerts: 10
        disableResolveMessage: true
