apiVersion: 1

policies:
  - orgId: 1
    receiver: whennawa-email
    group_by:
      - alertname
      - instance
      - uri
      - id
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 6h
    routes:
      - receiver: whennawa-email
        object_matchers:
          - ["cooldown", "=", "1h"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
      - receiver: whennawa-email
        object_matchers:
          - ["cooldown", "=", "2h"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 2h
      - receiver: whennawa-email
        object_matchers:
          - ["cooldown", "=", "6h"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 6h
